<?php
	$data = false;
	foreach($this->data['data'] as $submenu){
		if ($submenu['news_id'] == $this->selectedId){
			$data = $submenu;
			break;
		}
	}
	if (!$data) $data = $this->data['data'][0];
?>
<div class="news_content">
	<h3><?php echo $data['news_title'];?></h3>
	<table cellspacing="0" cellpadding="0" border="0" width="100%" class="news_content">
		<tr>
			<td valign="top">
				<?php echo $data['news_text'];?>
			</td>
			<td align="right" valign="top">
				<img class="news_photo" alt="<?php echo $data['news_title'];?>" src="/uploads/images/news/<?php echo $data['news_id'].'/middle/'.$data['news_photo'];?>"/>
			</td>
		</tr>
	</table>
</div>