<table cellspacing="0" cellpadding="0" border="0" width="100%" class="gallery_content"><tr>
<td width="40px">
	<a class="prev browse left"></a>
</td>
<td>
	<div class="scrollable">
		<div class="items">
			<div class="item_box">
				<table cellspacing="0" cellpadding="10" border="0" width="100%" class="slider_item"><tr>
					<?php
						$c=0; $k=0;
						foreach ($this->data as $photo){
							$c++;$k++;
							if ($c>4){
								$c=1;
								echo '</tr></table></div><div class="item_box"><table cellspacing="0" cellpadding="10" border="0" width="100%" class="slider_item"><tr>';
							}
							if ($k>2){
								$k=1;
								echo '</tr><tr>';
							}
							echo '<td><div class="item_content"><div class="item_photo"><a title="'.$photo['photos_title'].'" class="lightbox_img" href="/uploads/images/gallery/'.$photo['photos_id'].'/big/'.$photo['photos_core'].'"><img src="/uploads/images/gallery/'.$photo['photos_id'].'/middle/'.$photo['photos_core'].'" /></a></div><div class="item_title">'.$photo['photos_title'].'</div></div></td>';
						}
					?>
				</tr></table>
			</div>
		</div>
	</div>
</td>
<td width="40px">
	<a class="next browse right"></a>
</td>
</tr></table>