<div id="clientcar_${price_id}" car="${price_id}" class="client_car m_top15${vip:condition(" vip","")}">
	<div class="carStatusBox"/>
	<div class="rc_t inner_box"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="client_car_info_box">
			<div class="box car_info">
				<div class="ch_bx">
					<input class="cmp_chbx" type="checkbox" value="${price_id}"/>
				</div>
				<div class="sales p_rt">
					<div class="p_n"><a href="/buy/${type}/${mark.mark_link}/${model.model_link}/${price_id}/" target="_blank"><img width="80" height="52" src="${photo}" alt="Фото ${mark.mark_name} ${model.model_name}" /></a></div>
					<div class="link"><a href="javascript:void(0);" class="delete">удалить</a></div>
				</div>
				<div class="sales w_60">
					<div>${created_date:substr(0,10)}</div>
				</div>
				<div class="sales">
					<div class="reload" template="<?php echo $this->templatizate('${mark.mark_name}');?>">
						<?php echo $this->lastTmplt;?>
					</div>
				</div>
				<div class="sales">
					<div class="reload" template="<?php echo $this->templatizate('${model.model_name}');?>">
						<?php echo $this->lastTmplt;?>
					</div>
				</div>
				<div class="sales">
					<div class="reload" template="<?php echo $this->templatizate('${region}');?>">
						<?php echo $this->lastTmplt;?>
					</div>
				</div>
				<div class="sales w_60">
					<div class="reload" template="<?php echo $this->templatizate('${year}');?>">
						<?php echo $this->lastTmplt;?>
					</div>
				</div>
				<div class="sales w_60">
					<div style="padding-top:10px;">
						<strong class="reload" template="<?php echo $this->templatizate('${mileage}<br/>тыс.км.');?>">
							<?php echo $this->lastTmplt;?>
						</strong>
					</div>
				</div>
				<div class="sales w_60">
					<div style="padding-top:10px;">
						<strong class="reload" template="<?php echo $this->templatizate('${price}<br/>${currency}');?>">
							<?php echo $this->lastTmplt;?>
						</strong>
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div></div></div></div>
	</div></div></div></div>
</div>