<?php
	$data = false;
	foreach($this->data['data'] as $submenu){
		if ($submenu['feedback_id'] == $this->selectedId){
			$data = $submenu;
			break;
		}
	}
	if (!$data) $data = $this->data['data'][0];
?>
<?php if (isset($this->faq_error) && $this->faq_error){?>
<div class="submenu_error_text"><?php echo $this->faq_error;?></div>
<?php }elseif(isset($_POST) && $_POST){?>
<div class="submenu_success_text">Ваш отзыв успешно отправлен нашим модераторам. Спасибо!</div>
<?php }?>
<div class="feedback_content">
	<h3><?php echo $data['feedback_title'];?></h3>
	<div class="feedback_content_text">
		<?php echo $data['feedback_text'];?>
	</div>
</div>