<div class="AccountForm">
	<div class="label inner_label"><a href="#home">Мой кабинет</a> &rarr; Мои объявления</div>
	<div class="rc_t inner_box"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="user_content" id="user_content">
<?php /*			<h3>Ваши объявления:</h3>*/?>
			<p class="desc">Воспользуйтесь нашей системой <strong><a target="_blank" href="/info/vip/">VIP объявлений</a></strong> для эффективной продажи вашего автомобиля.</p>
			<div class="left addFilter">
				<a target="_blank" href="/sell/" class="add">Добавить объявление</a>
			</div>
<?php /*
			<div class="count">
				<span>Объявлений на странице:</span>
				<select onchange="javascript:document.location='/?p=&limit='+this.value+'';">
					<option value="10" selected="selected">10</option>
					<option value="30">30</option>
					<option value="50">50</option>
					<option value="100">100</option>
				</select>
			</div>
*/?>
			<div class="clear"></div>
			<div class="client_cars_paging_box"></div>
			<div class="box clear">
				<div class="filters_content">
					<div class="tc_tr"><div class="tc_br"><div class="tc_bl"><div class="tc_tl">
						<div class="head">
							<div class="sale b_ln">
								<div><strong>Фото</strong><?php /*<a class="setup" href="">Настройки</a>*/?></div>
							</div>
							<div class="sale w_60">
								<div><strong>Дата</strong></div>
							</div>
							<div class="sale">
								<div><strong>Марка</strong></div>
							</div>
							<div class="sale">
								<div><strong>Модель</strong></div>
							</div>
							<div class="sale">
								<div><strong>Регион</strong></div>
							</div>
							<div class="sale w_60">
								<div><strong>Год</strong></div>
							</div>
							<div class="sale w_60">
								<div><strong>Пробег</strong></div>
							</div>
							<div class="sale w_60 b_rn">
								<div><strong>Цена</strong></div>
							</div>
							<div class="clear"></div>
						</div>
					</div></div></div></div>
				</div>
			</div>
			<div class="client_cars_content"></div>
			<div class="client_cars_paging_box"></div>
		</div>
		<div class="clear"></div>
	</div></div></div></div>
	</div></div></div></div>
</div>