<div class="AccountForm">
	<div class="label inner_label"><a href="#home">Мой кабинет</a> &rarr; Избранные авто</div>
	<div class="rc_t inner_box"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="user_content" id="fav_content">
			<div class="client_fav_head">
				<div class="client_cmp_btn">
					<span>
						<a href="/cmp/">
							<div class="lnk">&nbsp;</div>
						</a>
					</span>
					<span>
						<a class="bottom_dashed" href="javascript:select_all_cars_on_page('<?php echo $this->type?>');">
							Выбрать все
						</a>
					</span>
					<span>
						<a class="bottom_dashed" href="javascript:select_none_cars_on_page('<?php echo $this->type?>');">
							Ни одного
						</a>
					</span>
				</div>
				<div class="client_cars_paging_box"></div>
			</div>
			<div class="box clear">
				<div class="filters_content">
					<div class="tc_tr"><div class="tc_br"><div class="tc_bl"><div class="tc_tl">
						<div class="head">
							<div class="ch_bx">
								<input type="checkbox"/>
							</div>
							<div class="sale b_ln">
								<div><strong>Фото</strong><?php /*<a class="setup" href="">Настройки</a>*/?></div>
							</div>
							<div class="sale w_60">
								<div><strong>Дата</strong></div>
							</div>
							<div class="sale">
								<div><strong>Марка</strong></div>
							</div>
							<div class="sale">
								<div><strong>Модель</strong></div>
							</div>
							<div class="sale">
								<div><strong>Регион</strong></div>
							</div>
							<div class="sale w_60">
								<div><strong>Год</strong></div>
							</div>
							<div class="sale w_60">
								<div><strong>Пробег</strong></div>
							</div>
							<div class="sale w_60 b_rn">
								<div><strong>Цена</strong></div>
							</div>
							<div class="clear"></div>
						</div>
					</div></div></div></div>
				</div>
			</div>
			<div class="client_cars_content"></div>
			<div class="client_cars_paging_box"></div>
		</div>
		<div class="clear"></div>
	</div></div></div></div>
	</div></div></div></div>
</div>