<div class="AccountForm">
	<div class="label inner_label">Мой кабинет</div>
	<div class="rc_t inner_box"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
	<div class="user_content">
		<div class="adm_menu_box cb">
			<div class="adm_hover_frame fl">
				<a href="#profile">
					<div class="adm_personal_icon_box cb"></div>
					<span>Личные данные</span>
				</a>
			</div>
			<div class="adm_hover_frame fl">
				<a href="#cars">
					<div class="adm_advert_icon_box cb"></div>
					<span>Мои объявления</span>
				</a>
			</div>
			<div class="adm_hover_frame fl">
				<a href="#favorites">
					<div class="adm_favor_icon_box cb"></div>
					<span>Избранные авто</span>
				</a>
			</div>
<?php /*
			<div class="adm_hover_frame fl">
				<a href="#">
					<div class="adm_compare_icon_box cb"></div>
					<span style="margin: 0pt 55px;">Сравнить</span>
				</a>
			</div>
			<div class="adm_hover_frame fl">
				<a href="#">
					<div class="adm_autos_icon_box cb"></div>
					<span style="margin: 0pt 56px;">Мои авто</span>
				</a>
			</div>
*/?>
		</div>
	</div>
	<div class="clear"></div>
	</div></div></div></div>
	</div></div></div></div>
</div>