<div class="header_contacts_icons">
	<a href="mailto:support@shariki.ua">
		<img src="/img/ico_mail.gif" alt="Отправить письмо" />
	</a>
	<a href="/tree/">
		<img src="/img/ico_tree.gif" alt="Дерево сайта" />
	</a>
	<a href="/">
		<img src="/img/ico_home.gif" alt="На главную" />
	</a>
</div>
<div class="header_contacts_content">
	<p>Тел.: (044) 482-18-40</p>
	<p>Тел.: (044) 482-11-24</p>
	<p>Тел.: (044) 482-18-40</p>
	<p>Круглосуточно</p>
</div>