<div class="header_contacts_icons">
	<a href="mailto:support@shariki.ua">
		<img src="/img/ico_mail.gif" alt="Отправить письмо" />
	</a>
	<a href="/tree/">
		<img src="/img/ico_tree.gif" alt="Дерево сайта" />
	</a>
	<a href="/">
		<img src="/img/ico_home.gif" alt="На главную" />
	</a>
	<a href="http://vkontakte.ru/club8577133">
		<img src="/img/ico_vk.gif" alt="Группа Вконтакте" />
	</a>
	<a href="http://sharikipo-kievski.blogspot.com/">
		<img src="/img/ico_blogger.gif" alt="Наш блог" />
	</a>
	<a href="http://www.facebook.com/home.php?sk=group_122730921132189&ref=ts">
		<img src="/img/ico_facebook.gif" alt="Наш блог" />
	</a>
</div>
<div class="header_contacts_content">
	<p>тел.: +380 44 482-11-24</p>
	<p>тел/факс: +380 44 482-18-40</p>
	<p>моб.: +380 67 401-33-02</p>
	<p>тел. магазина: +380 44 332-79-99</p>
	<p>тел.: +380 44 353-57-91 <span>(круглосуточно)</span></p>
</div>
