<div class="header_contacts_icons">
	<a href="mailto:support@shariki.ua">
		<img src="/img/ico_mail.gif" alt="Отправить письмо" />
	</a>
	<a href="/tree/">
		<img src="/img/ico_tree.gif" alt="Дерево сайта" />
	</a>
	<a href="/">
		<img src="/img/ico_home.gif" alt="На главную" />
	</a>
</div>
<div class="header_contacts_content">
	<p>тел.:+380 44 4821124</p>
	<p>тел/факс:+380 44 4821840</p>
	<p>моб.:+380 67 4013302</p>
	<p>(круглосуточно)</p>
</div>