<?php
	$data = false;
	foreach($this->data as $submenu){
		if ($submenu['team_id'] == $this->selectedId){
			$data = $submenu;
			break;
		}
	}
	if (!$data) $data = $this->data['data'][0];
?>
<div class="team_content">
	<h3><?php echo $data['team_name'];?> (<?php echo $data['team_title'];?>)</h3>
	<table cellspacing="0" cellpadding="0" border="0" width="100%" class="team_content">
		<tr>
			<td valign="top">
				<?php echo $data['team_text'];?>
			</td>
			<td align="right" valign="top">
				<img class="team_photo" title="<?php echo $data['team_name'];?>" alt="<?php echo $data['team_name'];?>" src="/uploads/images/team/<?php echo $data['team_id'].'/middle/'.$data['team_photo'];?>"/>
			</td>
		</tr>
	</table>
</div>