<div class="team_content">
	<?php foreach ($this->data as $team){ $link = '/team/detail/'.$team['team_id'].'/';?>
		<div class="team_content_item">
			<div class="team_content_photo"><a href="<?php echo $link; ?>"><img alt="<?php echo $team['team_name'];?>" src="/uploads/images/team/<?php echo $team['team_id'].'/middle/'.$team['team_photo'];?>"/></a></div>
			<div class="team_content_name"><a href="<?php echo $link; ?>"><?php echo $team['team_name'];?></a></div>
			<div class="team_content_text"><a href="<?php echo $link; ?>"><?php echo $team['team_title'];?></a></div>
		</div>
	<?php }?>
</div>
