<div class="UserMenu">
	<div class="filters_content">
	<div class="tc_tr"><div class="tc_br"><div class="tc_bl"><div class="tc_tl">
		<div class="content">
			<div class="column b_ln">
				<div><i>Вы вошли как:</i> <b><?php echo $this->userData['user']['email'];?></b></div>
				<div><a class="info" href="#profile">Личные данные</a></div>
			</div>
			<div class="column b_rn">
				<div><a class="advert" href="#cars">Мои объявления</a></div>
				<div><a class="all" href="#favorites">Избранные авто</a></div>
			</div>
			<?php /*
			<div class="column">
				<div><a class="filter" href="/adm/filter">Отслежвание (подбор авто)</a></div>
				<div><a class="share" href="/adm/share">Покажи свое авто</a></div>
			</div>
			<div class="column b_rn">
				<div class="left"><a class="action" href="/adm/action">Акция</a></div>
				<div class="attent left m_left10">Новинка</div>
			</div>
			*/?>
			<div class="clear"></div>
		</div>
	</div></div></div></div>
	</div>
</div>
<div id="clientPrev" style="display: none;">cars</div>
<div id="clientLoading" style="display: none;"></div>
<div id="clientLoader" style="display: none;"></div>
<div id="statusBox" class="statusBox"></div>
<div id="clientContent"></div>