<div id="clientcar_${price_id}" car="${price_id}" class="client_car m_top15${vip:condition(" vip","")}">
	<div class="carStatusBox"/>
	<div class="rc_t inner_box"><div class="rc_r"><div class="rc_b"><div class="rc_l">
	<div class="rc_tl"><div class="rc_tr"><div class="rc_br"><div class="rc_bl">
		<div class="client_car_info_box">
			<?php echo $this->render('client/cars/car/info.phtml');?>
		</div>
		<div class="car_edit_form">
		</div>
	</div></div></div></div>
	</div></div></div></div>
</div>