<div class="photo_box_${photos_id} preview${photos_main:condition(" select","")}">
	<img width="90" photo="${photos_id}" car="${photos_price_id}" order="${photos_order}" name="${photos_name}" subdir="${photos_subdir}" src="/uploads/images/${photos_subdir}/${photos_price_id}/small/${photos_name}" alt="фото автомобиля" />
	<a class="delete" href="javascript:void(0);" title="удалить"></a>
	<div>обложка</div>
</div>