<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Shariki.UA - Администрирование</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="en-US" />
<link href="/cms/js/extjs/resources/css/ext-all-car.css" media="screen"
	rel="stylesheet" type="text/css" />
<link href="/cms/css/desktop.css" media="screen" rel="stylesheet"
	type="text/css" />
<link href="/cms/css/icons.css" media="screen" rel="stylesheet"
	type="text/css" />
<!--[if IE]>
<style type="text/css"> 
.x-form-field {vertical-align: baseline;}
</style>
<![endif]-->

<!-- GC -->
<!-- LIBS -->
<script type="text/javascript"
	src="/cms/js/extjs/adapter/ext/ext-base.js"></script>
<!-- ENDLIBS -->

<script type="text/javascript" src="/cms/js/extjs/ext-all.js"></script>

<!-- LOGIN FORM -->
<script type="text/javascript" src="/cms/js/desktop/login.js"></script>
<script type="text/javascript" src="/cms/js/extjs/src/locale/ext-lang-ru.js"></script>

</head>
<body scroll="no">
<div class="admin_body_box">
<div id="loader" style="display: none;"></div>

<div id="loading">
<div class="loading-indicator"></div>

</div>
</div>
<script type="text/javascript">
Ext.onReady(function() {
	Ext.get('loading').hide();
});
</script>
</body>
</html>
