<div class="tree_box">
	<div class="tree_title">Карта сайта</div>
	<div class="tree_content">
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/">Главная</a></div>
			<div class="tree_subitem_box">
				<div class="tree_subitem_title"><a href="/calendar/">Календарь праздников</a></div>
				<div class="tree_subitem_title"><a href="/news/">Новости</a></div>
			</div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/services/">Услуги</a></div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/gallery/">Галерея</a></div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/market/">Розничная торговля</a></div>
			<div class="tree_subitem_box">
<?php foreach ($this->market as $item){$link = '/market/category/'.$item['marketc_id'].'/';?>
				<div class="tree_subitem_title"><a href="<?php echo $link;?>"><?php echo $item['marketc_title'];?></a></div>
<?php } ?>
			</div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/news/">Новости</a></div>
			<div class="tree_subitem_box">
				<div class="tree_subitem_title"><a href="/news/archive/">Архив новостей</a></div>
			</div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/feedback/">Отзывы</a></div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/team/">Наша команда</a></div>
		</div>
		<div class="tree_item_box">
			<div class="tree_item_title"><a href="/contacts/">Контактная информация</a></div>
		</div>
	</div>
</div>