<?php
	$data = false;
	foreach($this->data as $submenu){
		if ($submenu['services_id'] == $this->selectedId){
			$data = $submenu;
			break;
		}
	}
	if (!$data) $data = $this->data[0];
?>
<div class="services_content">
	<h3><?php echo $data['services_title'];?></h3>
	<table cellspacing="0" cellpadding="0" border="0" width="100%" class="services_content">
		<tr>
			<td valign="top">
				<?php echo $data['services_text'];?>
			</td>
			<td align="right" valign="top">
				<img class="services_photo" alt="<?php echo $data['services_title'];?>" src="/uploads/images/services/<?php echo $data['services_id'].'/middle/'.$data['services_photo'];?>"/>
			</td>
		</tr>
	</table>
<?php if ($this->gallery){ ?>
	<table cellspacing="0" cellpadding="0" border="0" class="gallery_content"><tr>
		<td width="40px">
			<a class="prev browse left"></a>
		</td>
		<td>
			<div class="scrollable">
				<div class="items">
<?php
	foreach ($this->gallery as $photo){
	?>
	<div class="item_box">
		<div class="item_photo">
			<a title="<?php echo $photo['photos_title']; ?>" class="lightbox_img" href="/uploads/images/services/<?php echo $photo['photos_parent_id']; ?>/big/<?php echo $photo['photos_name']; ?>">
				<img src="/uploads/images/services/<?php echo $photo['photos_parent_id']; ?>/small/<?php echo $photo['photos_name']; ?>" />
			</a>
		</div>
		<div class="item_title">
			<?php echo $photo['photos_title']; ?>
		</div>
	</div>
							<?php
	    	}
	?>
</div>
</div>
</td>
<td width="40px">
	<a class="next browse right"></a>
</td>
</tr></table>
<?php } ?>
</div>