<?php
	$data = false;
	foreach($this->data['data'] as $submenu){
		if ($submenu['calendar_id'] == $this->selectedId){
			$data = $submenu;
			break;
		}
	}
	if (!$data) $data = $this->data['data'][0];
?>
<div class="calendar_content">
	<h3><span><?php echo $this->date.' - ';?></span><?php echo $data['calendar_title'];?></h3>
	<table cellspacing="0" cellpadding="0" border="0" width="100%" class="calendar_content">
		<tr>
			<td valign="top">
				<?php echo $data['calendar_text'];?>
			</td>
			<td align="right" valign="top">
				<img class="calendar_photo" alt="<?php echo $data['calendar_title'];?>" src="/uploads/images/calendar/<?php echo $data['calendar_id'].'/middle/'.$data['calendar_photo'];?>"/>
			</td>
		</tr>
	</table>
</div>