<div class="calendar_title">Календарь праздников  - <b><?php echo $this->date;?></b></div>
<div class="calendar_content">
<?php
	if (count($this->data['data'])){
		foreach ($this->data['data'] as $calendar){ $link = '/calendar/detail/'.$calendar['calendar_id'].'/';
?>
			<table cellspacing="0" cellpadding="0" border="0" width="100%" class="calendar_item"><tr>
				<td class="calendar_item_photo" valign="top">
					<a href="<?php echo $link;?>">
						<img alt="<?php echo $calendar['calendar_title'];?>" src="/uploads/images/calendar/<?php echo $calendar['calendar_id'].'/small/'.$calendar['calendar_photo'];?>" />
					</a>
				</td>
				<td class="calendar_item_content" valign="top">
					<div class="calendar_item_title">
						<a href="<?php echo $link;?>">
							<?php echo $calendar['calendar_title'];?>
						</a>
					</div>
					<div class="calendar_item_text">
						<?php echo $calendar['calendar_description'];?>
					</div>
				</td>
			</tr></table>
<?php
		}
	}
	else {
?>
		<div class="calendar_empty">Не найдено событий!</div>
<?php
	}
?>
</div>